### ISSUE TITLE
Github action erroring on new flag github-actions

### ISSUE THREAD

**Issue by JoshuaJackson-jobvite** [trufflesecurity/trufflehog#1236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
trufflehog 3.31.2-rc.2 due to use of latest by the action.yml.

### Trace Output

```
TruffleHog
failed Apr 3, 2023 in 10s
2s
3s
1s
0s
Run trufflesecurity/trufflehog@main
/usr/bin/docker run --name ghcriotrufflesecuritytrufflehoglatest_199e9b --label 6c0442 --workdir /github/workspace --rm -e "INPUT_PATH" -e "INPUT_BASE" -e "INPUT_HEAD" -e "INPUT_EXTRA_ARGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/repo/repo":"/github/workspace" ghcr.io/trufflesecurity/trufflehog:latest  "git" "file://./" "--since-commit" "main" "--branch" "HEAD" "--fail" "--no-update" "--github-actions" "--debug --only-verified"
trufflehog: error: unknown long flag '--github-actions', try --help
```

### Expected Behavior

Trufflehog should output github-actions output as expected not have a missing flag

### Actual Behavior

trufflehog fails to execute due to missing github-actions flag

### Steps to Reproduce

Run a job currently with the defined standard behaviors around the action:
```

name: Security Scanning
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
```

Pull the latest version and run the following:
```
docker run ghcr.io/trufflesecurity/trufflehog:latest git --help
```
observe lack of available flag.

## Environment
Github action

## Additional Context
Looks like there's a compounding set of problems here:
1) the use of latest for the action. With the revert from the input's version (with a default) would help here prevent new fixues from breaking others
2) https://github.com/trufflesecurity/trufflehog/pull/1201 brought in the changes but appears that the options are not being validated correctly for the new flag behavior and thus getting the no such arg's available.
2a) Note I've not validated further than the basics of when the changes came in and would need to review the golang code more fully to make a better determination, sorry I've not done that yet.
