### ISSUE TITLE
Not finding passwords and tokens

### ISSUE THREAD

**Issue by mohanss08** [trufflesecurity/trufflehog#1317]
I'm using `trufflehog_3.33.0_linux_amd64.tar.gz` to detect the passwords and tokens. 

Actually i have hard-coded tokens & passwords and committed them into my github repository. But when i tried to scan it is not finding tokens and passwords.

```
$ ./trufflehog git git@github-company.com:org-demo/test.git --only-verified
2023-05-02T09:57:50+05:30       info-0  trufflehog      loaded decoders {"count": 3}
2023-05-02T09:57:50+05:30       info-0  trufflehog      loaded detectors        {"total": 737, "verification_enabled": 737, "verification_disabled": 0}
2023-05-02T09:57:50+05:30       info-0  trufflehog      possible duplicate detector configured  {"detector": "Square"}
🐷🔑🐷  TruffleHog. Unearth your secrets. 🐷🔑🐷
```

In my repository files i have passwords & tokens like below format.

```
USERNAME="user"
PASSWORD="password"

HTTP_USER="user1"
HTTP_TOKEN="DRFuteQw$#riYhte69AwerDdf-$"
```

Can I know what is the issue with my command? Why it is not finding custom password & token?

Any help would be appreciated

**Comment by mohanss08** [comment]
Any help will be helpful.

**Comment by zricethezav** [comment]
@mohanss08 
> Can I know what is the issue with my command? Why it is not finding custom password & token?

```
USERNAME="user"
PASSWORD="password"

HTTP_USER="user1"
HTTP_TOKEN="DRFuteQw$#riYhte69AwerDdf-$"
```

These are generic credentials. Trufflehog does not support scanning generic credentials by default. 

@Atrejoe 
> I would expect the secrets in app1.props to be found too.

`password=MySAP@ssw0rd!` in a `.props` file does not give enough information to determine what detector that secret is for which is why it is not detected.

**Comment by sadams-evi** [comment]
what is the status of this ticket I am experiencing the same issue

**Comment by zricethezav** [comment]
@sadams-evi see, the response I gave above: https://github.com/trufflesecurity/trufflehog/issues/1317#issuecomment-1584903339

Trufflehog is scanning as expected. If you would like to detect something like `password=MySAP@ssw0rd!` in a `.props file` , I suggest you write a custom regex detector: https://github.com/trufflesecurity/trufflehog#regex-detector-example

Closing the issue as this is the intended behavior.

**Comment by zricethezav** [comment]
@sadams-evi YAML only at this time

**Comment by mohanss08** [comment]
@sadams-evi - Please leave an example steps to deploy custom regex detector for my use case. It would be helpful.

**Comment by sadams-evi** [comment]
Can you explain to me what "verify" is in the example provided 
```
# config.yaml
detectors:
- name: hog detector
  keywords:
  - hog
  regex:----> (IS THIS WHERE THE REGEX GOES ?)
    adjective: hogs are (\S+)
  verify: ---> (what is needed to input here ?) 
  - endpoint: http://localhost:8000/
    # unsafe must be set if the endpoint is HTTP
    unsafe: true
    headers:
    - 'Authorization: super secret authorization header'
```

@zricethezav

**Comment by sadams-evi** [comment]
@zricethezav  if you could let me know if this is correct formatting 

I am trying to detect regex pattern for 
"API key": "([a-zA-Z0-9]{32})"

```
# config.yaml
detectors:
- name: hog detector
  keywords:
  - API key
  regex:-
    adjective: "([a-zA-Z0-9]{32})"
    unsafe: true
    headers:
    - 'Authorization: super secret authorization header'
```

**Comment by zricethezav** [comment]
I encourage you to try it out first. Use regex101 to see if your regex are working as intended.


But you could use something like this if all you care about is the regex and keyword:
```
# config.yaml
detectors:
- name: custom api detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
```

`verify` is an optional check to see if your secret is valid and/or live.

**Comment by zricethezav** [comment]
looks good to me

**Comment by sadams-evi** [comment]
also one last question @zricethezav  
If I am only interested in scanning the last commit, is the correct code line : 
```
trufflehog --fail  --config ./trufflehog/trufflehog-rules.yaml  --only-verified git file:///$PWD --regex --since-commit HEAD
```

**Comment by sadams-evi** [comment]
@zricethezav  when the following config.yaml file with regex is run 

```
# config.yaml
detectors:
- name: custom api detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
- name: Slack Webhook
  keywords:
  - slack
  regex:
    adjective: "\\bhttps:\\/\\/hooks\\.slack\\.com\\/services\\/T[a-zA-Z0-9_]{8}\\/[a-zA-Z0-9_]{10}\\/[a-zA-Z0-9_]{24}\\b"
- name: Heroku API detector
  keywords:
  - Heroku API 
  regex:
    adjective: "?<![A-Za-z0-9])[A-Za-z0-9_-]{20}\\.[A-Za-z0-9_-]{80}(?![A-Za-z0-9_-]"
- name: Heroku API Key detector
  keywords:
  - Heroku API Key
  regex:
    adjective: "[hH][eE][rR][oO][kK][uU].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"
- name: AWS access key detector
  keywords:
  - AWS access key
  regex:
    adjective: "AKIA[0-9A-Z]{16}"
- name: AWS secret access key detector
  keywords:
  - AWS secret access key
  regex:
    adjective: "\\b[A-Za-z0-9/+=]{40}\\b"
- name: Github detector
  keywords:
  - Github key
  regex:
    adjective: "\\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]){0,38})?[a-zA-Z0-9]\\/[a-zA-Z0-9-_]{1,100}\\b"
- name: Cloudflare API Key detector
  keywords:
  - Cloudflare API Key
  regex:
    adjective: "^[a-zA-Z0-9-]{40}$"
- name: Google Gmail API Key detector
  keywords:
  - Google Gmail API Key
  regex:
    adjective: "AIza[0-9A-Za-z\\-_]{35}"

```

an error is produce : 
```
 error   trufflehog      error parsing the provided configuration file   {"error": "regex 'adjective': error parsing regexp: missing argument to repetition operator: `?`"}
```
