### ISSUE TITLE
Multiple Custom Regex in config.yaml file 

### ISSUE THREAD

**Issue by sadams-evi** [trufflesecurity/trufflehog#1392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version
3.39.0

### Trace Output
I am using to following configuration file for custom regex 
```
# config.yaml
detectors:
- name: custom api detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
detectors:
- name: Slack Webhook
  keywords:
  - slack
  regex:
    adjective: "\\bhttps:\\/\\/hooks\\.slack\\.com\\/services\\/T[a-zA-Z0-9_]{8}\\/[a-zA-Z0-9_]{10}\\/[a-zA-Z0-9_]{24}\\b"
detectors:
- name: Heroku API detector
  keywords:
  - Heroku API 
  regex:
    adjective: "?<![A-Za-z0-9])[A-Za-z0-9_-]{20}\\.[A-Za-z0-9_-]{80}(?![A-Za-z0-9_-]"
detectors:
- name: Heroku API Key detector
  keywords:
  - Heroku API Key
  regex:
    adjective: "[hH][eE][rR][oO][kK][uU].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}"
detectors:
- name: AWS access key detector
  keywords:
  - AWS access key
  regex:
    adjective: "AKIA[0-9A-Z]{16}"
detectors:
- name: AWS secret access key detector
  keywords:
  - AWS secret access key
  regex:
    adjective: "\\b[A-Za-z0-9/+=]{40}\\b"
detectors:
- name: Github detector
  keywords:
  - Github key
  regex:
    adjective: "\\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]){0,38})?[a-zA-Z0-9]\\/[a-zA-Z0-9-_]{1,100}\\b"
detectors:
- name: Cloudflare API Key detector
  keywords:
  - Cloudflare API Key
  regex:
    adjective: "^[a-zA-Z0-9-]{40}$"
detectors:
- name: Google Gmail API Key detector
  keywords:
  - Google Gmail API Key
  regex:
    adjective: "AIza[0-9A-Za-z\\-_]{35}"
```
My YAML is complaining, about unique map keys. 

When referring to https://github.com/trufflesecurity/trufflehog#regex-detector-example there is no example of how to apply multiple custom rules. I am wondering if this config format is correct ?

**Comment by zricethezav** [comment]
@sadams-evi what is the output

**Comment by zricethezav** [comment]
```
# config.yaml
detectors:
- name: custom api detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
detectors:
- name: Slack Webhook
  keywords:
  - slack
  regex:
    adjective: "\\bhttps:\\/\\/hooks\\.slack\\.com\\/services\\/T[a-zA-Z0-9_]{8}\\/[a-zA-Z0-9_]{10}\\/[a-zA-Z0-9_]{24}\\b"
detectors:
```

`detectors` should not be used more than one

```
# config.yaml
detectors:
- name: custom api detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}":
- name: Slack Webhook
  keywords:
  - slack
  regex:
    adjective: "\\bhttps:\\/\\/hooks\\.slack\\.com\\/services\\/T[a-zA-Z0-9_]{8}\\/[a-zA-Z0-9_]{10}\\/[a-zA-Z0-9_]{24}\\b"
...
```
