### ISSUE TITLE
trufflehog pre-commit hook not failing on AWS credentials

### ISSUE THREAD

**Issue by varunchandak** [trufflesecurity/trufflehog#1544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### TruffleHog Version

trufflehog 3.45.0
### Trace Output
https://gist.github.com/varunchandak/333caea3a055068226676137be1d5062

### Expected Behavior
trufflehog should fail with AWS credentials present in a file during commit

### Actual Behavior
trufflehog passes with AWS credentials present in a file during commit

### Steps to Reproduce

 1. Create new **private** repo
 2. commit `.pre-commit-config.yaml` with below contents
 ```
repos:
- repo: local
  hooks:
  - id: trufflehog
    name: TruffleHog
    description: Detect secrets in your data.
    entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
    language: system
    stages: ["commit", "push"]
```
3. ensure `trufflehog` cli is installed. For me it is at `/opt/homebrew/bin/trufflehog` and in PATH
4. clone the repo locally
5. generate a readonly access/secret key in AWS and save it in a file
6. add the file in the repo
7. do `git add .` and `git commit`, trufflehog should throw an error with detected credentials

## Environment
 * OS: macOS Ventura 13.4.1
 * Version 13.4.1

### References

* #0000
