### ISSUE TITLE
Scanning generic credentials

### ISSUE THREAD

**Issue by mohanss08** [trufflesecurity/trufflehog#1640]
In my github repository i have passwords & tokens in below given format.

For example,

File: `password.sh`
```
USERNAME="user.name"
PASSWORD="password012"
```
File: token.sh
```
HTTP_USER="user1"
HTTP_TOKEN="DRFuteQw$#riYhte69AwerDdf-$"
````
So to detect password & tokens, i have custom regex given below.

```
# config.yaml
detectors:
- name: custom password detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
```
```
./trufflehog git git@github-company.com:org-demo/test.git --config config.yaml --only-verified
```
But it didn't detected the passwords. What could be the problem? Any suggestion to detect my custom passwords & tokens would be helpful.

**Comment by zricethezav** [comment]
hi @mohanss08, couple of things that might help solve this mystery.

1. You are running a `git` scan, did you commit the fake secret?
2. You have `--only-verified` flagged. Since you are using a custom config with no api validation this flag isn't necessary and might cause incorrect behavior

**Comment by mohanss08** [comment]
@zricethezav 
1. Yes commits are having custom secrets like in above given format.
2. Had tried without `--only-verified` flag, still didn't detect.

Possibly can you help me with `config.yaml` for my use case? Thanks in advance.

**Comment by zricethezav** [comment]
```
# config.yaml
detectors:
- name: custom password detector
  keywords:
  - api
  regex:
    adjective: "[a-zA-Z0-9]{32}"
```

You have `api` for keywords. 

```
USERNAME="user.name"
PASSWORD="password012"
```
and 
```
HTTP_USER="user1"
HTTP_TOKEN="DRFuteQw$#riYhte69AwerDdf-$"
```

Does not contain `api`. This is why your secret isn't getting picked up.

**Comment by mohanss08** [comment]
I see,  Do you mean the `keyword` should be the acutal secret used inside the files?

**Comment by zricethezav** [comment]
No, the keyword is a filter used to reduce false positives. In this case for a generic secret you can use something like `token`, `password`, or `user`.

It's in the documentation: https://github.com/trufflesecurity/trufflehog#regex-detector-alpha

**Comment by mohanss08** [comment]
@zricethezav - Now i have `config.yaml` like below.
```
detectors:
- name: custom password detector
  keywords:
  - username
  - password
  - token
  regex:
    adjective: "[a-zA-Z0-9]{32}"
```

Still it is not detected. Still something am i missing? Please advise.
