### ISSUE TITLE
Scanning remote repo only scans 1 branch

### ISSUE THREAD

**Issue by DavidMay121** [trufflesecurity/trufflehog#184]
I was testing out trufflehog and found the following behavior, which seems like a bug:

1) I cloned a remote git repo, created a new branch, and then appended a SHA hash (which I know is found by the entropy check) to an existing file, which I then committed and pushed to the remote repo.

2) I then ran trufflehog against the remote repo, and it wasn't scanning anything but the origin/master branch.

```$ trufflehog https://github.REDACTED.org/REDACTED.git | grep Branch -B 3
Date: 2019-09-23 11:54:43
Hash: REDACTED
Filepath: ansible_cloudformation/config/users.all.yaml
Branch: origin/master
```

If I grep for just `Branch`, the entirety of all trufflehog findings are tied to the master branch.

3) However, if I specify a branch (--branch=truffle-test), it finds it just fine

```$ trufflehog --branch=truffle-test https://github.REDACTED.org/REDACTED.git | grep Branch -B 3
Date: 2019-10-04 12:47:26
Hash: REDACTED
Filepath: sonar-project.properties
Branch: FETCH_HEAD
--
Date: 2019-09-23 11:54:43
Hash: REDACTED
Filepath: ansible_cloudformation/config/users.all.yaml
Branch: FETCH_HEAD
```

Note the second entry, which was the first entry that showed up when no branch was specified.

4) I then tried the local approach. I recloned the repo, ran `git branch` and verified that it was tracking this new branch that I just pushed (truffle-test). When I run `trufflehog .` against the local repo, though, it does not find this entry.

**Comment by madhavajay** [comment]
@DavidMay121 I had the same issue.
Its weird because the code says it scans the remote branches but it doesn't seem to.

truffleHog.py
```
    if branch:
        branches = repo.remotes.origin.fetch(branch)
    else:
        branches = repo.remotes.origin.fetch()

    for remote_branch in branches:
```

For now what I have done is a work around.

You can either use git --clone so your local copy has everything or run a one liner:
https://stackoverflow.com/questions/67699/how-to-clone-all-remote-branches-in-git
```
git branch -a | grep -v HEAD | perl -ne 'chomp($_); s|^\*?\s*||; if (m|(.+)/(.+)| && not $d{$2}) {print qq(git branch --track $2 $1/$2\n)} else {$d{$_}=1}' | csh -xfs
```
You will need perl and csh.

I ended up putting this into a .gitlab-ci.yml
```
trufflehog:
    image: 
        name: python:3-alpine
        entrypoint: [""]
    dependencies: []
    stage: trufflehog
    before_script:
        - apk add --no-cache git perl tcsh && pip install trufflehog
    script:
        - git branch -a | grep -v HEAD | perl -ne 'chomp($_); s|^\*?\s*||; if (m|(.+)/(.+)| && not $d{$2}) {print qq(git branch --track $2 $1/$2\n)} else {$d{$_}=1}' | csh -xfs
        - trufflehog --regex --entropy=False ./
    tags:
        - security
        - trufflehog
```

Of course in theory once your repo is clean and you're doing CI you can potentially rely on it only scanning the current HEAD which is what your CI should deliver to the working directory. But right now I need to prove it's working on a new branch where the security issue is on another unmerged branch.

Good luck!
