### ISSUE TITLE
Docker Source Config fails

### ISSUE THREAD

**Issue by sherlocksecurity** [trufflesecurity/trufflehog#2598]
When i try to use custom config for docker, getting parse error ..

Command: trufflehog docker --image linuxbsdfreak/cpol-amd64 --only-verified --debug --config=config.yaml

Config file:

```
sources:
- connection:
    '@type': type.googleapis.com/sources.Docker
    basicAuth:
      password: dckr_pat_sfsfdsafas
      username: testes
    images:
    - trufflesecurity/secrets
  name: Docker
  scanPeriod: 12h
  type: SOURCE_TYPE_DOCKER
  verify: true
```
