### ISSUE TITLE
Add Documentation for Running TruffleHog in GitLab CI

### ISSUE THREAD

**Issue by RoseSecurity** [trufflesecurity/trufflehog#2600]
## Description

Would it be possible to add documentation regarding the integration of TruffleHog into GitLab CI pipelines?

## Example

GitLab CI Pipeline:

```yaml
stages:
  - security
  
security-secrets:
  stage: security
  allow_failure: false
  image: alpine:latest
  variables:
    SCAN_PATH: "." # Set the relative path in the repo to scan
  before_script:
    - apk add --no-cache git curl jq
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trufflehog filesystem "$SCAN_PATH" --only-verified --fail --json | jq
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
   ```
