### ISSUE TITLE
Some custom regex doesn't work

### ISSUE THREAD

**Issue by AmrSec** [trufflesecurity/trufflehog#3259]
i have the following config.yaml file which contain custom regex to find cloud buckets in many ways. When test it on Repos contain i want want, it doesn't give me the correct result results.

<h2>Doesn't match the following:</h2>

BUCKET.storage.googleapis.com
storage.googleapis.com/BUCKET
s3.amazonaws.com/BUCKET

<h2>Match the following:</h2>

s3://bucket
gc://bucket
BUCKET.s3.amazonaws.com

<h2>Config File</h2>

```
# config.yaml
detectors:
  - name: "Custom S3 Bucket Detector"
    keywords:
      - aws
      - goolge
    regex:
      bucket: s3://[a-zA-Z0-9.-]+|gs://[a-zA-Z0-9.-]+|[a-zA-Z0-9.-]+\.storage\.googleapis\.com|[a-zA-Z0-9.-]+\.s3\.amazonaws\.com|storage\.googleapis\.com\/[a-zA-Z0-9.-]+|s3\.amazonaws\.com\/[a-zA-Z0-9.-]+
```

- The regex works for me with many "regex tester" but does't work with Trufflehog
- There are many broken links in your go scripts but i don't know the issue from it or not. such as
https://github.com/trufflesecurity/trufflehog/v3/pkg/pb/custom_detectorspb
github.com/hashicorp/golang-lru/v2
