### ISSUE TITLE
Apply custom-detectors to specific file types (via inclusion or exclusion)

### ISSUE THREAD

**Issue by mtcolman** [trufflesecurity/trufflehog#3302]
Please review the [Community Note](https://github.com/trufflesecurity/trufflehog/blob/main/.github/community_note.md) before submitting

## Description
Is it possible to apply regex detectors to specific filetypes? the main use case I have for this is that some filetypes specify password/secret strings without quotes around them, whilst in other filetypes this would be a parameter and thus safe for inclusion.

### Preferred Solution
If we could specify in the config.yaml:
```
detectors:
- name: custom password detector
  keywords:
  - username
  - password
  - token
  regex:
    adjective: "[a-zA-Z0-9]{32}"
  exclude_types: [".py", ".txt", ".example"]
```

### Additional Context
So that I could define many detectors and for each individually whether to apply this to certain file types. Then I can clone/run this against an entire directory. I don't want to exclude the files from a scan, I just want to exclude them from specific detectors.

#### References
N/A

Thanks!
