### ISSUE TITLE
Make Github Action customizable

### ISSUE THREAD

**Issue by timmeinerzhagen** [trufflesecurity/trufflehog#540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Problem to be Addressed

The current options for usage of the GitHub Actions for Trufflehog are very limited. Only the options `path`, `base`, and `head` are allowed. This is not enough for many use cases.

## Description of the Preferred Solution

Additional options like `no-verify`, `include-` / `exclude-paths`, and output options would be needed to make it usable in many cases.
Ideally, an custom output for the GitHub Action for Trufflehog could leverage [Job Summary for GitHub Actions](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), which would be a lot more usable instead of having to rely on the runner logs.

### Option 1: Include the current options that are available for the cli in the GitHub Action 

Example
```yml
- name: TruffleHog OSS
  uses: trufflesecurity/trufflehog@v3.4.3
  with:
    path: ./
    base: ${{ github.event.repository.default_branch }}
    no-verify: true
    output: json
```

### Option 2: Add a parameter like `options` to the GitHub Action that could be used to just specify cli options that will just be appended when trufflehog gets executed.

Example
```yml
- name: TruffleHog OSS
  uses: trufflesecurity/trufflehog@v3.4.3
  with:
    path: ./
    base: ${{ github.event.repository.default_branch }}
    options: --no-verify --json
```

### References

* [Current options for TruffleHog OSS Github Action](https://github.com/trufflesecurity/trufflehog#trufflehog-oss-github-action)
* [Job Summary for GitHub Actions](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/)
