### ISSUE TITLE
excluding a file/folder from scanning in github action

### ISSUE THREAD

**Issue by sjgupta19** [trufflesecurity/trufflehog#675]
Hi, how do I exlcude particular directory from scanning in my github repo? I am using the following trufflehog setup in github actions - 
- 

name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ env.BRANCH }}
          head: HEAD
          args: --only-verified

how can I use exclude-path flag in my github workflow?

**Comment by sjgupta19** [comment]
some help here...

**Comment by mac2000** [comment]
look at [action.yml](https://github.com/trufflesecurity/trufflehog/blob/main/action.yml#L33) the action itself just runs docker image and passes whatever you want via extra args, with that in place you may achieve that like so:

```yaml
- uses: trufflesecurity/trufflehog@main
  with:
    path: public
    base: ${{ github.event.repository.default_branch }}
    head: HEAD
    extra_args: --debug --exclude-paths=/path/to/exclude.txt
```

where `/path/to/exclude.txt` should be a file containing new line delimited regular expressions to exclude from checks, aka

**exclude.txt**

```
node_modules
.log
```

to check it locally you may run something like that:

```bash
docker run --rm -v "${PWD}:/code" ghcr.io/trufflesecurity/trufflehog:latest git file:///code --since-commit main --branch HEAD --fail --exclude-paths=/code/exclude.txt --debug --no-update
```
